fix ci/cd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,6 +35,10 @@ jobs:
       - name: unit testing
         if: always()
         run: npm run test:unit
+      - name: Verify files
+        run: |
+          ls -la reports/
+          [ -f reports/index.html ] || (echo "index.html not found" && exit 1)
       - name: Setup Pages
         uses: actions/configure-pages@v5
         if: always()
